### ISSUE TITLE
TSIS stuck on 0% 

### ISSUE THREAD

**Issue by sk1350** [wyguo/TSIS#3]
Hello, 
after i press the scoring button, the app gets stuck on 0% without giving me an error. 
"Step 1: Search for intersection points with Mean expression...
 Searching ...0%"
What could the issue be?

**Comment by wyguo** [comment]
Hi,
Could you please give me more details of your input datasets? I need to see the data structure to figure out the issue.
Best regards.

**Comment by sk1350** [comment]
Hello, 
I am using stringtie produced transcript counts from Xenopus RNAseq data. Since this is an exploratory analysis I only have 2 replicates for each of 4 of my time points. The gene annotation file comes from Ensembl

**Comment by wyguo** [comment]
Hi,
Could you please send me a screenshot or a subset of your input files for TSIS: (a) transcript isoform expression and (b) two column table of gene-isoform association (see https://github.com/wyguo/TSIS#input-data-files for input file details).
Best

**Comment by sk1350** [comment]
Hello 

Here are the first 15 lines of my transcript isoform expression and two column gene-isoform association tables .

Sample	SRR489440	SRR489444	SRR489462	SRR489464	SRR489465	SRR489466	SRR489470	SRR489471
Stage	10	16	10	13	13	16	24	24	
ENSXETT00000039734	0	0	0	0	0	0	0	0	
ENSXETT00000028013	0	0	0	0	0	0	0	0	
ENSXETT00000039732	0	0	0	0	0	0	0	0	
ENSXETT00000028006	0	0	0	0	0	0	0	0	
ENSXETT00000039721	637.2512243	1016.861757	764.8807036	1212.732061	1257.266161	1271.383873	1092.382468	1107.126575	
ENSXETT00000039716	0	0	0	0	0	0	0	0	
ENSXETT00000027992	0	0	0	0	0	0	0	0	
ENSXETT00000027985	0	0	0	0	0	0	0	0	
ENSXETT00000039623	0	0	0	0	0	0	0	0	
ENSXETT00000039601	0	0	0	0	0	0	0	0	
ENSXETT00000039617	0	0	0	0	0	0	0	0	
ENSXETT00000027878	0	5.373361098	0	0	0	7.866645698	106.7733673	92.11645005	
ENSXETT00000027884	0	0	0	0	0	0	0	0	

gene_name	t_name
.	ENSXETT00000039734
.	ENSXETT00000028013
ppp1r3c.2	ENSXETT00000039732
.	ENSXETT00000028006
utp15	ENSXETT00000039721
mccc1	ENSXETT00000039716
golga1	ENSXETT00000027992
wdr38	ENSXETT00000027985
fbxo8	ENSXETT00000039623
slc16a5	ENSXETT00000039601
fbxo8	ENSXETT00000039617
cdr2l	ENSXETT00000027878
fbxo8	ENSXETT00000027884
fbxo8	ENSXETT00000039609

Kind regards, 
Sofia

**Comment by wyguo** [comment]
Hi,
Your input files are not correct. Please read the user manual to prepare the input files: https://github.com/wyguo/TSIS#input-data-files
 I have reformat your input: 
(A) The expression matrix table, please use replicates labels to distinguish the samples of different replicates:
Samples	rep1	rep2	rep1	rep2	rep1	rep2	rep1	rep2
Stage	10	10	13	13	16	16	24	24
ENSXETT00000039734	0	0	0	0	0	0	0	0
ENSXETT00000028013	0	0	0	0	0	0	0	0
ENSXETT00000039732	0	0	0	0	0	0	0	0
ENSXETT00000028006	0	0	0	0	0	0	0	0
ENSXETT00000039721	637.2512243	764.8807036	1212.732061	1257.266161	1016.861757	1271.383873	1092.382468	1107.126575
ENSXETT00000039716	0	0	0	0	0	0	0	0
ENSXETT00000027992	0	0	0	0	0	0	0	0
ENSXETT00000027985	0	0	0	0	0	0	0	0
ENSXETT00000039623	0	0	0	0	0	0	0	0
ENSXETT00000039601	0	0	0	0	0	0	0	0
ENSXETT00000039617	0	0	0	0	0	0	0	0
ENSXETT00000027878	0	0	0	0	5.373361098	7.866645698	106.7733673	92.11645005
ENSXETT00000027884	0	0	0	0	0	0	0	0
(B) The gene-transcript association information, the gene name column must be all filled

gene_name	t_name
Gene1	ENSXETT00000039734
Gene2	ENSXETT00000028013
ppp1r3c.2	ENSXETT00000039732
Gene3	ENSXETT00000028006
utp15	ENSXETT00000039721
mccc1	ENSXETT00000039716
golga1	ENSXETT00000027992
wdr38	ENSXETT00000027985
fbxo8	ENSXETT00000039623
slc16a5	ENSXETT00000039601
fbxo8	ENSXETT00000039617
cdr2l	ENSXETT00000027878
fbxo8	ENSXETT00000027884

Best
