### ISSUE TITLE
LOG2 TPM transformation?

### ISSUE THREAD

**Issue by kmothera** [wyguo/TSIS#4]
Hi, @wyguo  

We have been using TSIS with great results. The analysis seems very promising. One question though:
do you recommend log transforming the TPM abundances or keep them as is? I'm not entirely  how the normalized abundances are used within TSIS.

Thank you!

**Comment by wyguo** [comment]
Hi,
In our own analysis, we used TPM values for TSIS analysis (see the details in our publication http://www.plantcell.org/content/30/7/1424 for details). It gave very promising results. We also used the TPM values to plot the profiles of genes and transcripts. So by using the TPM values for TSIS will give a consensus isoform switch visualisation in these profile plots. My suggestion would be you can try both TPMs and log-transfomred TPMs for TSIS and pick the most proper one according to your interpration workflow. 
Best
